### ISSUE TITLE
Can't find sdk golang 

### ISSUE THREAD

**Issue by YouROK** [consulo/consulo-google-go#3]
System:
OS: 24.04.1 LTS (Noble Numbat)

Kernel: Linux yourok-work 6.8.0-50-generic #51-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov  9 17:58:29 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Golang: go version go1.23.4 linux/amd64

 Consulo:
  version = 2024.12
  build number = 3695
  build date = December 18, 2024
 Plugins:
  com.intellij.regexp = 1974
  consulo = 3695
  consulo.desktop.awt = 3695
  consulo.google.go = 2980

I created a golang test project
When creating the sdk the selection was empty
When selecting the sdk in the settings it does not find it
 
![screenshot](https://github.com/user-attachments/assets/62e42192-9e37-4e19-8c40-dd349647706e)

**Comment by VISTALL** [comment]
Hello. I will check it - maybe today :)

**Comment by VISTALL** [comment]
Fixed in last nightly build - wait for it
